# Generated by Django 5.0.3 on 2024-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DateTimeField(),
        ),
    ]
